apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffxisearch-deployment
  labels:
    app: ffxisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffxisearch
  template:
    metadata:
      labels:
        app: ffxisearch
    spec:      
      containers:      
      - name: ffxisearch
        image: kuberegistry:32000/phoenix:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 54002
        resources:
          limits:
            memory: "1000M"
            cpu: "1"
          requests:
            memory: "200M"
            cpu: "0.25"
        env:
        - name: MYSQL_HOST
          value: "10.0.0.30"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "xidb"
        - name: MYSQL_LOGIN
          value: "ffxi"
        - name: MYSQL_PASSWORD
          value: "SquareEnix81"        
        - name: SERVERNAME
          value: "PhoenixReborn"
        - name: MSG_SERVER
          value: "ffxilogin-service"
        - name: APP
          value: "AUCTION"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: ffxishare
  name: ffxisearch-service
spec:
  selector:
    app: ffxisearch
  ports:
    - name: search
      protocol: TCP
      port: 54002
  sessionAffinity: ClientIP
  type: LoadBalancer