apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffxigameb-deployment
  labels:
    instance: b
    app: ffxigame
spec:
  replicas: 1
  selector:
    matchLabels:
      instance: b
      app: ffxigame
  template:
    metadata:
      labels:
        instance: b
        app: ffxigame
    spec:      
      containers:
      - name: ffxigame
        image: registry.imgdelivered.com/phoenix:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 54231
          protocol: UDP
        resources:
          limits:
            memory: "4000M"
            cpu: "4"
          requests:
            memory: "500M"
            cpu: "1"
        env:
        - name: MYSQL_HOST
          value: "10.0.0.30"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "xidb"
        - name: MYSQL_LOGIN
          value: "ffxi"
        - name: MYSQL_PASSWORD
          value: "SquareEnix81"        
        - name: SERVERNAME
          value: "PhoenixReborn"
        - name: MSG_SERVER
          value: "ffxilogin-service"
        - name: GAME_PORT
          value: "54231"
        - name: LOGIN_DATA_SERVER
          value: "ffxilogin-service"
        - name: LOGIN_AUTH_SERVER
          value: "ffxilogin-service"
        - name: LOGIN_VIEW_SERVER
          value: "ffxilogin-service"
        - name: LOGIN_CONF_SERVER
          value: "ffxilogin-service"
        - name: ZMQ_SERVER
          value: "ffxilogin-service"
        - name: APP
          value: "GAME"
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ffxigameb-service
spec:
  selector:
    app: ffxigame
    instance: b
  ports:
    - name: mapport
      protocol: UDP
      port: 54231
  sessionAffinity: ClientIP
  type: LoadBalancer