apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: ds-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-game
  template:
    metadata:
      labels:
        app: ds-game
    spec:
      containers:
      - name: ds-game
        image: hargrave81/phoenix
        env:
        - name: MYSQL_HOST
          value: phoenix.eastus2.cloudapp.azure.com
        - name: MYSQL_LOGIN
          value: ffxi
        - name: MYSQL_PORT
          value: "3309"
        - name: MYSQL_DATABASE
          value: dspdb
        - name: MYSQL_PASSWORD
          value: Squareenix81
        - name: SERVERNAME
          value: PhoenixProject
        - name: APP
          value: GAME
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: ds-game  
  ports:
    - name: stream
      port: 54230         
      protocol: UDP     
  sessionAffinity: ClientIP   
  type: LoadBalancer