apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: ds-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-search
  template:
    metadata:
      labels:
        app: ds-search
    spec:
      containers:
      - name: ds-search
        image: hargrave81/phoenix        
        env:
        - name: MYSQL_HOST
          value: phoenix.eastus2.cloudapp.azure.com
        - name: MYSQL_LOGIN
          value: ffxi
        - name: MYSQL_PORT
          value: "3309"
        - name: MYSQL_DATABASE
          value: dspdb
        - name: MYSQL_PASSWORD
          value: Squareenix81
        - name: SERVERNAME
          value: PhoenixProject
        - name: APP
          value: AUCTION
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: ds-search  
  ports:
    - name: searchport
      port: 54002      
      protocol: TCP
  sessionAffinity: ClientIP   
  type: LoadBalancer