require("scripts/globals/monstertpmoves")
require("scripts/globals/status")
require("scripts/globals/msg")
require("scripts/globals/utils")

function onMobSpawn(pet)
    local master = pet:getMaster()        
    local mLvl = master:getMainLvl()
    local foodPower = 3 + (mLvl / 10)
    pet:addStatusEffect(dsp.effect.DEF_BOOST,foodPower*2.2,0,9600,0,0)
    pet:addStatusEffect(dsp.effect.STR_BOOST,foodPower,0,9600,0,0)
    pet:addStatusEffect(dsp.effect.INT_BOOST,foodPower,0,9600,0,0)
    pet:addStatusEffect(dsp.effect.MAX_HP_BOOST,foodPower,0,9600,0,0)
    local diff = (pet:getMaxHP() - pet:getHP())
    pet:addHP(diff)
end